vscode:
  extensions:
    - WakaTime.vscode-wakatime@2.2.1:5pOtrx5Q2i2UzuEg6Qu0Ug==
    - trixnz.vscode-lua@0.12.4:uBDTdyX2wB6WfiegrI9OMA==
    - ms-vsliveshare.vsliveshare@1.0.1653:sanGRimQDgMUJY9D83Je5g==